version: '3'
services:


  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data-test:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MAX_SESSION_AGE: 13140000

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  selenium:
    image: "selenium/standalone-chrome:3.6.0-bromine"
    ports:
      - "5900:5900"
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
